### ISSUE TITLE
GNOME 44 runtime EOL (20 March 2024), please update

### ISSUE THREAD

**Issue by GAJansen** [flathub/org.gnucash.GnuCash#87] opened 2024-04-30 12:43 UTC
Please update to a newer runtime:

❯ flatpak update                                                                                                                                                                      ─╯
Looking for updates…
Info: org.gnome.Platform//44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gnucash.GnuCash

**Comment by fellen** [comment] 2024-04-30 14:52
Duplicate of issue #86

**Closed by fellen** 2024-04-30 14:52 UTC
