### ISSUE TITLE
Update runtime to v41

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnucash.GnuCash#44] opened 2021-09-26 00:25 UTC

**Comment by travier** [comment] 2022-01-04 17:35
This is now fixed (see https://github.com/flathub/org.gnucash.GnuCash/pull/48).

**Comment by picsel2** [comment] 2022-01-25 19:17
Nice! But unfortunately the build of the master branch fails currently and build bot [does not provide any useful output](https://flathub.org/builds/#/builders/8/builds/8647).

**Comment by hfiguiere** [comment] 2022-01-25 19:20
Unfortunately the build has been purge (too old). I just retriggered a new one. And if it fails, I can have a further look at what the problem is.


(sadly nobody gets notified when a build fail outside of a PR)

**Comment by jralls** [comment] 2022-01-25 21:17
A missing close-quote on the GNUCASH_BUILD_ID. Fixed and a new build is running. Thanks for the heads-up.

**Closed** 2022-04-02 17:25 UTC
